(function(){
'use strict';
var LIMIT=30000,RESULT_AD='planet-bus-result-interstitial',EXTRA_AD='planet-bus-extra-play',EXTRA_FLOW='planet-bus-ad-extra',SHARE_FLOW='planet-bus-share-point',CLEAR_BENEFIT='planet-bus-clear-1p';
var ROUTES={
'9007':{bus:'9007',type:'직행좌석',origin:'운중동먹거리촌',destination:'서울역',direction:'서울역행',split:[3,5],questions:[q('운중초',['서현역','모란시장']),q('운중행정복지센터',['광교호수공원','신촌동']),q('판교박물관',['수원시청','남위례역']),q('엔씨·안랩',['경기대','복정고']),q('판교역',['잠실새내','태평오거리']),q('고속터미널',['아주대','삼평교']),q('명동',['운중도서관','수서역']),q('서울시청',['월드컵경기장','야탑역'])]},
'1007-1':{bus:'1007-1',type:'직행좌석',origin:'대광빌리지',destination:'잠실역(롯데월드)',direction:'잠실역행',split:[5,3],questions:[q('아주대',['모란역','삼평교']),q('수원월드컵경기장',['명동','위례자이']),q('광교역',['서울시청','판교박물관']),q('운중행정복지센터',['수서역','농수산물시장']),q('판교박물관',['대광빌리지','야탑역']),q('판교제2테크노밸리',['고속터미널','아주대']),q('수서역',['광교역사공원','모란고개']),q('삼전역',['운중초','수원시청'])]},
'4500':{bus:'4500',type:'직행좌석',origin:'수원버스터미널',destination:'사송동종점',direction:'사송동행',split:[6,2],questions:[q('수원시청역',['서울역','삼평교']),q('아주대',['남위례역','운중초']),q('수원월드컵경기장',['명동','모란시장']),q('경기대',['수서역','판교역']),q('광교역사공원',['복정고','서울시청']),q('운중행정복지센터',['잠실새내','농수산물시장']),q('야탑역',['광교역','고속터미널']),q('모란역',['판교박물관','위례자이'])]},
'315':{bus:'315',type:'일반버스',origin:'금토동삼거리',destination:'복정역 환승센터',direction:'복정역행',split:[2,6],questions:[q('판교제2테크노밸리',['수원시청','운중초']),q('삼평교',['명동','광교역']),q('야탑역',['아주대','수서역']),q('모란역',['판교박물관','서울시청']),q('남위례역',['경기대','고속터미널']),q('래미안위례',['농수산물시장','삼전역']),q('위례자이',['광교호수공원','운중도서관']),q('복정고',['수원월드컵경기장','판교역'])]}};
function q(name,distractors){return{name:name,distractors:distractors};}function $(id){return document.getElementById(id);}function wait(ms){return new Promise(function(r){setTimeout(r,ms);});}function ok(r){return !!(r&&r.ok===true);}function data(r){return r&&r.data?r.data:{}}function shuffle(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t;}return a;}function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
var state={routeKey:'9007',bridge:null,channel:'WEB',remaining:null,index:0,wrong:0,startAt:0,timer:null,ended:false,busy:false,runId:0,score:0,resultSeq:null,clearIssueSeq:'',ranking:null,shareBusy:false,adBusy:false};function route(){return ROUTES[state.routeKey];}
function show(name){document.querySelectorAll('.screen').forEach(function(el){el.classList.toggle('active',el.id==='screen-'+name);});window.scrollTo(0,0);}function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){$('toast').classList.remove('show');},2200);}function setDriving(on){$('driver-view').classList.toggle('driving',on);$('driver-view').classList.toggle('stopped',!on);}function setStatus(t){$('drive-status').textContent=t;}
function routeNodes(r){var a=[{name:r.origin,kind:'terminal'}],i;for(i=0;i<r.split[0];i++)a.push({name:r.questions[i].name,kind:'quiz'});a.push({name:'SK플래닛',kind:'planet'});for(i=r.split[0];i<8;i++)a.push({name:r.questions[i].name,kind:'quiz'});a.push({name:r.destination,kind:'terminal'});return a;}
function renderCourse(){var r=route(),order=['9007','1007-1','4500','315'];$('route-tabs').innerHTML=order.map(function(k){return'<button class="route-tab '+(k===state.routeKey?'active':'')+'" data-route="'+k+'"><b>'+k+'</b><span>'+esc(ROUTES[k].destination)+'</span></button>';}).join('');$('route-number').textContent=r.bus;$('route-type').textContent=r.type;$('route-origin').textContent=r.origin;$('route-destination').textContent=r.destination;var nodes=routeNodes(r),quizNo=0,planetIndex=r.split[0]+1,pts=[];$('route-stops').innerHTML=nodes.map(function(s,i){var badge=s.kind==='quiz'?String(++quizNo):s.kind==='planet'?'경유':i===0?'출':'도';return'<li class="'+s.kind+'"><i>'+badge+'</i><span>'+esc(s.name)+'</span></li>';}).join('');nodes.forEach(function(s,i){var x,y;if(i===0){x=150;y=395}else if(i===planetIndex){x=165;y=215}else if(i===nodes.length-1){x=170;y=35}else if(i<planetIndex){var t=i/planetIndex;x=150+Math.sin(i*1.25)*62;y=395-180*t}else{var t2=(i-planetIndex)/(nodes.length-1-planetIndex);x=165+Math.sin(i*1.25)*62;y=215-180*t2}pts.push([x,y]);});var d=pts.map(function(p,i){return(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)}).join(' ');$('route-map-line').innerHTML='<path class="map-route-shadow" d="'+d+'"></path><path class="map-route-path" d="'+d+'"></path>';Array.from($('route-stops').children).forEach(function(li,i){li.style.left=(pts[i][0]/320*100)+'%';li.style.top=(pts[i][1]/430*100)+'%';});}
function bridgeReady(){return new Promise(function(resolve){if(window.OGOGBridge)return resolve(window.OGOGBridge);var done=false;function fin(){if(done)return;done=true;window.removeEventListener('ogogbridge:ready',fin);resolve(window.OGOGBridge||null)}window.addEventListener('ogogbridge:ready',fin);setTimeout(fin,4000);});}
async function report(type,score,body){try{return state.bridge&&state.bridge.execution?await state.bridge.execution.report({type:type,score:score,resultCode:body&&body.resultCode,resultType:body&&body.resultType,body:body}):null}catch(e){return null}}
async function refreshParticipation(){if(!state.bridge||!state.bridge.participation){state.remaining=1;$('main-chance').textContent='출발 준비가 끝났어요';$('start-btn').disabled=false;return;}try{var d=data(await state.bridge.participation.getState());state.remaining=typeof d.remainingCount==='number'?d.remainingCount:null;$('main-chance').textContent=state.remaining==null?'출발 준비가 끝났어요':'오늘 '+state.remaining+'번 운전할 수 있어요';$('start-btn').disabled=d.playable===false;$('ad-main-btn').classList.toggle('hidden',d.playable!==false);}catch(e){$('main-chance').textContent='출발 준비가 끝났어요';$('start-btn').disabled=false;}}
async function loadMyRank(source){if(source&&source.ranking)state.ranking=source.ranking;else if(state.bridge&&state.bridge.ranking&&state.bridge.ranking.getMyRank)try{var r=await state.bridge.ranking.getMyRank();state.ranking=ok(r)?data(r):null}catch(e){state.ranking=null}renderRank();}
function renderRank(){var r=state.ranking||{},rank=Number(r.rank),count=Number(r.participantCount);$('main-rank').textContent=Number.isFinite(rank)?(Number.isFinite(count)?count.toLocaleString('ko-KR')+'명 중 '+rank.toLocaleString('ko-KR')+'위':'현재 '+rank.toLocaleString('ko-KR')+'위'):'플레이 후 순위가 생겨요';$('result-rank').textContent=Number.isFinite(rank)?(Number.isFinite(count)?count.toLocaleString('ko-KR')+'명 중 '+rank.toLocaleString('ko-KR')+'위':'현재 '+rank.toLocaleString('ko-KR')+'위'):'순위 집계 중';}
async function openRanking(){var m=$('ranking-modal');m.classList.remove('hidden');m.setAttribute('aria-hidden','false');$('ranking-list').innerHTML='';$('ranking-status').classList.remove('hidden');$('ranking-status').textContent='실시간 순위를 불러오는 중…';try{if(!state.bridge||!state.bridge.ranking||!state.bridge.ranking.getTopRanks)throw new Error();var d=data(await state.bridge.ranking.getTopRanks({limit:100}));if(!Array.isArray(d.items))throw new Error();$('ranking-period').textContent=d.periodName||'현재 랭킹';$('ranking-list').innerHTML=d.items.slice(0,20).map(function(it){return'<li class="'+(it.mine?'mine':'')+'"><i>'+it.rank+'위</i><span>'+esc(it.nickname||'참가자')+'</span><b>'+Number(it.score||0).toLocaleString('ko-KR')+'점</b></li>';}).join('');$('ranking-status').classList.add('hidden');}catch(e){$('ranking-status').textContent='순위표를 잠시 불러오지 못했어요.';}}
function closeRanking(){$('ranking-modal').classList.add('hidden');$('ranking-modal').setAttribute('aria-hidden','true');}
function renderHeader(){var r=route();$('game-bus-number').textContent=r.bus;$('game-direction').textContent=r.direction;}
function updateTimer(){if(state.ended)return;var left=Math.max(0,LIMIT-(performance.now()-state.startAt));$('timer').textContent=(left/1000).toFixed(1);if(left<=0)finish(false);}
async function prepareGame(){if(state.busy)return;state.busy=true;var start=await report('START',0,{entryPath:'start',gameId:'planet-bus-route-challenge',routeNumber:route().bus,timeLimitMs:LIMIT});if(start&&start.ok===false){toast('게임을 시작하지 못했어요.');state.busy=false;return;}renderHeader();state.busy=false;await beginDrive();}
async function beginDrive(){state.runId++;state.index=0;state.wrong=0;state.score=0;state.ended=false;state.busy=false;state.clearIssueSeq='';state.resultSeq=null;clearInterval(state.timer);$('timer').textContent='30.0';$('progress-bar').style.width='0%';show('play');setDriving(true);setStatus(route().origin+' 출발!');state.startAt=performance.now();state.timer=setInterval(updateTimer,50);await wait(450);approach(state.runId);}
function renderChoices(){var x=route().questions[state.index],arr=shuffle([x.name].concat(x.distractors));$('game-progress').textContent=(state.index+1)+' / 8';$('progress-bar').style.width=(state.index/8*100)+'%';$('choice-remaining').textContent='3개 선택 가능';$('choices').innerHTML=arr.map(function(n){return'<button class="choice-button" data-name="'+esc(n)+'">'+esc(n)+'</button>';}).join('');}
async function approach(run){if(state.ended||run!==state.runId)return;state.busy=false;setDriving(true);$('choice-panel').classList.remove('hidden');$('checkpoint').className='checkpoint';$('flag-name').textContent='?';renderChoices();setStatus('달리면서 정류장 이름을 맞혀주세요');await wait(80);$('checkpoint').classList.add('rolling');var idx=state.index;await wait(1800);if(state.ended||run!==state.runId||idx!==state.index)return;if(!$('checkpoint').classList.contains('passed')){$('checkpoint').classList.remove('rolling');$('checkpoint').classList.add('hold');setDriving(false);setStatus('정답을 골라주세요');}}
async function chooseStop(btn){if(state.ended||state.busy||btn.disabled)return;var answer=route().questions[state.index];if(btn.dataset.name!==answer.name){state.wrong++;btn.disabled=true;btn.classList.add('wrong');$('choice-remaining').textContent=$('choices').querySelectorAll('button:not(:disabled)').length+'개 남았어요';$('warning').classList.add('show');setTimeout(function(){$('warning').classList.remove('show');},950);return;}state.busy=true;btn.classList.add('correct');$('flag-name').textContent=answer.name;$('checkpoint').classList.remove('rolling','hold');setStatus(answer.name+' 정답!');await wait(150);$('choice-panel').classList.add('hidden');setDriving(true);$('checkpoint').classList.add('passed');state.index++;$('progress-bar').style.width=(state.index/8*100)+'%';await wait(390);if(state.index===route().split[0])await passPlanet();if(state.index>=8){finish(true);return;}state.busy=false;approach(state.runId);}
async function passPlanet(){if(state.ended)return;$('checkpoint').className='checkpoint rolling';$('flag-name').textContent='SK플래닛';$('choice-panel').classList.add('hidden');setStatus('SK플래닛 경유');await wait(1750);$('checkpoint').classList.remove('rolling');$('checkpoint').classList.add('passed');await wait(700);$('checkpoint').className='checkpoint';}
function calcScore(success,elapsed){var base=state.index*1000,bonus=success?Math.floor(Math.max(0,LIMIT-elapsed)/10):0,penalty=state.wrong*100;return Math.max(0,base+bonus-penalty);}
async function finish(success){if(state.ended)return;state.ended=true;state.runId++;clearInterval(state.timer);setDriving(false);$('choice-panel').classList.add('hidden');var elapsed=Math.min(LIMIT,Math.max(0,performance.now()-state.startAt));state.score=calcScore(success,elapsed);setStatus(success?route().destination+' 도착!':'운행 시간 종료!');var res=await report('COMPLETE',state.score,{entryPath:'result',resultType:success?'SUCCESS':'FAIL',resultCode:success?'CLEAR_30SEC':'TIMEOUT',routeNumber:route().bus,elapsedMs:Math.round(elapsed),correctCount:state.index,wrongCount:state.wrong,totalQuestions:8,timeLimitMs:LIMIT});var d=data(res);state.resultSeq=d.resultSeq!=null?d.resultSeq:null;var benefit=(d.benefits||[]).find(function(x){return x.benefitId===CLEAR_BENEFIT});state.clearIssueSeq=benefit&&benefit.benefitIssueSeq!=null?String(benefit.benefitIssueSeq):'';await loadMyRank(d);await showResultAd();renderResult(success,elapsed);await refreshParticipation();}
async function showResultAd(){show('ad');await wait(450);try{if(state.bridge&&state.bridge.ad&&state.bridge.ad.show){var r=await state.bridge.ad.show({placementId:RESULT_AD}),d=data(r);if(ok(r)&&d.transactionId&&state.bridge.ad.complete)await state.bridge.ad.complete({placementId:RESULT_AD,transactionId:d.transactionId,completed:true});}}catch(e){}await wait(450);}
function renderResult(success,elapsed){show('result');$('result-label').textContent=success?'MISSION COMPLETE':'TIME OVER';$('result-title').textContent=success?route().destination+' 도착!':'30초 운행 종료';$('result-score').textContent=state.score.toLocaleString('ko-KR');$('result-message').textContent=success?'8개 정류장을 모두 통과했어요!':'통과한 정류장 기준으로 점수가 저장됐어요.';$('result-correct').textContent=state.index+' / 8';$('result-wrong').textContent=state.wrong+'회';$('result-time').textContent=(elapsed/1000).toFixed(1)+'초';$('clear-point-btn').classList.toggle('hidden',!state.clearIssueSeq);$('clear-point-btn').disabled=false;renderRank();updateExtraButtons();}
async function claimClearPoint(){if(!state.clearIssueSeq||!state.bridge||!state.bridge.reward)return;var b=$('clear-point-btn');b.disabled=true;try{var r=await state.bridge.reward.claim({benefitIssueSeq:state.clearIssueSeq});if(!ok(r))throw new Error();state.clearIssueSeq='';b.classList.add('hidden');toast('완주 1P가 적립됐어요!');}catch(e){b.disabled=false;toast('1P 적립을 완료하지 못했어요.');}}
function drawShareCard(){var c=$('share-canvas'),x=c.getContext('2d');x.fillStyle='#0d1c25';x.fillRect(0,0,800,800);x.fillStyle='#c7ff39';x.font='bold 46px sans-serif';x.fillText(route().bus+' PLANET BUS',60,95);x.fillStyle='#fff';x.font='bold 86px sans-serif';x.fillText(state.score.toLocaleString('ko-KR')+'점',60,250);x.font='bold 38px sans-serif';x.fillText(route().origin+' → SK플래닛',60,360);x.fillText('→ '+route().destination,60,415);x.fillStyle='#9fb3bd';x.font='32px sans-serif';x.fillText('통과 '+state.index+'/8 · 오답 '+state.wrong+'회',60,520);x.fillStyle='#118a58';x.fillRect(60,610,680,92);x.fillStyle='#fff';x.font='bold 36px sans-serif';x.fillText('너도 30초 노선 챌린지!',118,668);}
async function shareResult(){if(state.shareBusy)return;state.shareBusy=true;try{drawShareCard();if(state.bridge&&state.bridge.share&&state.bridge.share.captureAndUploadImage&&state.bridge.share.requestKakao&&state.bridge.share.complete){var cap=await state.bridge.share.captureAndUploadImage({targetId:'share-canvas'}),cd=data(cap);if(!ok(cap)||!cd.captureToken)throw new Error();var payload={captureToken:cd.captureToken,flowId:SHARE_FLOW,shareChannel:'KAKAO',shareOptions:{title:'플래닛 버스 노선 챌린지',description:route().bus+'번 '+state.score+'점! 너도 도전해봐!',buttonTitle:'나도 운행하기'}};if(state.resultSeq!=null)payload.resultSeq=state.resultSeq;var req=await state.bridge.share.requestKakao(payload);if(!ok(req))throw new Error();var done={flowId:SHARE_FLOW,shared:true,shareChannel:'KAKAO'};if(data(req).shareId)done.shareId=data(req).shareId;if(state.resultSeq!=null)done.resultSeq=state.resultSeq;if(!ok(await state.bridge.share.complete(done)))throw new Error();toast('공유 완료! 1P가 곧 반영돼요.');}else if(navigator.share){await navigator.share({title:'플래닛 버스 노선 챌린지',text:route().bus+'번 '+state.score+'점!'});}else toast('앱에서 공유하면 1P를 받을 수 있어요.');}catch(e){if(!(e&&e.name==='AbortError'))toast('공유를 완료하지 못했어요.');}finally{state.shareBusy=false;}}
async function grantExtra(){if(state.adBusy)return;state.adBusy=true;try{if(!state.bridge||!state.bridge.ad||!state.bridge.participation)throw new Error();var r=await state.bridge.ad.show({placementId:EXTRA_AD}),d=data(r);if(!ok(r))throw new Error();var done=await state.bridge.ad.complete({flowId:EXTRA_FLOW,placementId:EXTRA_AD,transactionId:d.transactionId,adNetwork:d.adNetwork,completed:true});if(!ok(done))throw new Error();await state.bridge.participation.getExtraChance();await refreshParticipation();toast('운행 기회 1회가 추가됐어요!');show('route');}catch(e){toast('추가 기회를 받지 못했어요.');}finally{state.adBusy=false;}}
function updateExtraButtons(){var noChance=state.remaining===0;$('ad-main-btn').classList.toggle('hidden',!noChance);$('ad-result-btn').classList.toggle('hidden',!noChance);}
function bind(){$('route-select-btn').onclick=function(){show('route');renderCourse();};$('intro-back-btn').onclick=function(){show('main');};$('route-tabs').onclick=function(e){var b=e.target.closest('.route-tab');if(b){state.routeKey=b.dataset.route;renderCourse();}};$('ranking-card').onclick=openRanking;$('ranking-close').onclick=closeRanking;$('ranking-modal').onclick=function(e){if(e.target===$('ranking-modal'))closeRanking();};$('start-btn').onclick=prepareGame;$('choices').onclick=function(e){var b=e.target.closest('.choice-button');if(b)chooseStop(b);};$('clear-point-btn').onclick=claimClearPoint;$('share-btn').onclick=shareResult;$('ad-main-btn').onclick=grantExtra;$('ad-result-btn').onclick=grantExtra;$('retry-btn').onclick=prepareGame;$('home-btn').onclick=function(){show('route');renderCourse();};}
async function boot(){renderCourse();bind();state.bridge=await bridgeReady();if(state.bridge&&state.bridge.profile)state.channel=state.bridge.profile.channel||'WEB';$('ranking-card').disabled=!(state.bridge&&state.bridge.ranking);await refreshParticipation();await loadMyRank();updateExtraButtons();}
boot();
})();
